config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  put '/users/:user_id/todos/:id/completed', to: 'todos#completed'
  put '/users/:user_id/todos/:id/uncompleted', to: 'todos#uncompleted'
  # get '/users/:user_id/todos/search', to: 'todos#search'
  root 'home#index'
  resources :users do
      resources :todos
  end
  resources :sessions

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  ActiveRecord::Base.include_root_in_json = false
  validates_presence_of :title, :deadline
  belongs_to :user
  def init
    self.completed  ||= false
    self.overdue ||= false         #will set the default value only if it's nil
  end

  def self.check_overdue(user_id)
    todos = []
    all_todos = User.find(user_id).todos
    all_todos.each do |todo|
      deadline = DateTime.strptime(todo.deadline.to_s, "%Y-%m-%d %H:%M:%S %Z")
      if deadline <= DateTime.now
        todo.update(overdue: true)
      end
      todos.push(todo)
    end
    todos
  end

  def is_completed
    self.update(completed: true)
  end

  def is_uncompleted
    self.update(completed: false)
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates_uniqueness_of :username
    validates_presence_of :username
    has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

    def authorize
        redirect_to login_url, alert: "Not authorized" if current_user.nil?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    def create
        user = User.find_by_username(params[:username])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to "/users/#{user.id}/todos", notice: "Log In"
        else
            @error = "username or password is incorrect"
            render "new"
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_url, notice: "Log Out"
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_filter :authorize
    def index
      todos = Todo.check_overdue(params[:user_id])
      if params[:search]
        todos = search_by_keywords(todos, params[:search])
      end
      @todos = todos.nil? ? nil : find_uncompleted_todos(todos)
      @recent_todos = todos.nil? ? nil : find_recent(todos, 3)
      @date = params[:date] ?  Date.parse(params[:date]) : Date.today
    end

    def show
        @todo = Todo.find_by_id(params[:id])
    end
    def new
        @todo = Todo.new
    end

    def create
        @todo = User.find(params[:user_id]).todos.new(todo_params)
        if @todo.save
            redirect_to "/users/#{params[:user_id]}/todos"
        else
            render 'new'
        end
    end

    def destroy
        Todo.find_by_id(params[:id]).destroy!
        respond_to do |format|
          format.html { redirect_to user_todos_path, notice: 'Item was successfully deleted.' }
        end
    end

    def completed
      @todo = Todo.find_by_id(params[:id])
      @todo.is_completed
      respond_to do |format|
        format.html { redirect_to "/users/#{params[:user_id]}/todos/#{params[:id]}" }
        format.json { render json: @todo.as_json(root: false) }
      end
    end

    def uncompleted
      @todo = Todo.find_by_id(params[:id])
      @todo.is_uncompleted
      todos = Todo.check_overdued(params[:user_id])
      completed_todos = todos.select { |todo| todo.completed == true }
      recent_todos = completed_todos.sort_by(&:updated_at).reverse!.take(3)
      respond_to do |format|
        format.html { redirect_to "/users/#{params[:user_id]}/todos/#{params[:id]}" }
        format.json { render json: { "todo" => @todo.as_json(root: false), "completed_todos" => recent_todos.as_json} }
      end
    end

    def edit
        @todo = Todo.find_by_id(params[:id])
    end

    def update
        @todo = Todo.find_by_id(params[:id])
        if @todo.update(todo_params)
            redirect_to user_todo_path
        else
            render 'edit'
        end
    end

    private
        def todo_params
            params.require(:todo).permit(:title, :deadline, :completed, :detail)
        end

        def search_by_keywords(todos, search)
          results = []
          todos.each do |todo|
            if todo[:title].include?(search) || todo[:detail].include?(search)
              results.push(todo)
            end
          end
          results.sort_by(&:created_at)
        end
        def find_uncompleted_todos(todos)
          uncompleted_todos = todos.select { |todo| todo.completed == false }
          results = {}
          uncompleted_todos.sort_by(&:deadline).each do |todo|
            key = todo.deadline.to_date.to_s.to_sym
            if results.key?(key)
              results[key].push(todo)
            else
              results[key] = []
              results[key].push(todo)
            end
          end
          results
        end

        def find_recent(todos, number)
          completed_todos = todos.select { |todo| todo.completed == true }
          completed_todos.sort_by(&:updated_at).reverse!.take(number)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        render "new"
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to "/users/#{@user.id}/todos", notice: "Thank you for signing up!"
        else
            render "new"
        end
    end

    private
        def user_params
            params.require(:user).permit(:username, :password, :password_confirmation)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w(Sun Mon Tue Wed Thu Fri Sat)
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
        header + week_rows
    end

    def header
      content_tag :ul, class: "weekdays" do
        HEADER.map { |day| content_tag :li, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :ul, class: "days" do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :li, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      if day == Date.today
        classes << "today"
      elsif day.month > date.month && day.year < date.year
        classes << "prevmonth"
      elsif day.month < date.month && day.year > date.year
        classes << "nextmonth"
      elsif day.month < date.month
        classes << "prevmonth"
      elsif day.month > date.month
        classes << "nextmonth"
      end
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>TODOs</h1>

<div class="col-md-8">
    <h3>A Web App To-Do List. The project goals are:</h3>
    <hr>
    <ul>
      <li>As a user, I can add a TODO to the list.</li>
      <li>As a user, I can see all the TODOs on the list in an overview.</li>
      <li>As a user, I can drill into a TODO to see more information about the TODO.</li>
      <li>As a user, I can delete a TODO.</li>
      <li>As a user, I can mark a TODO as completed.</li>
      <li>As a user, when I see all the TODOs in the overview, if today's date is past the TODO's deadline, highlight it.</li>
    </ul>
</div><br />

<div class="col-md-8">
    <h3>Getting Started</h3>
    <hr>
    <p>
        Followed the <kbd>MVC</kbd> design pattern hardly to perform a solid design process. Used <kbd>TDD</kbd> for development.
        First I was looking at the <kbd>scenario</kbd>.
    </p>
    <p>
        The first step: <kbd>Enumerate</kbd>. (I listed all possible features.)
    </p>
    <ul>
      <li>Add todo</li>
      <li>Display todos</li>
      <li>View certain todo</li>
      <li>Delete todo</li>
      <li>Mark a todo as completed</li>
      <li>Hightlight the passed todo task</li>
      <li>Search a todo</li>
      <li>Show todos based on their deadline</li>
      <li>Show unfinished todos in separate column</li>
      <li>User can login/register</li>
      <li>Coming up todos</li>
    </ul>
    <p>
        Now, second steps: <kbd>Sort</kbd>. I want to make the <kbd>MVP</kbd>, so I need to make sure it has all the required feature before I add more to it.
    </p>
    <ul>
      <li>User can login/register</li>
      <li>Add todo</li>
      <li>Display todos</li>
      <li>View certain todo</li>
      <li>Delete todo</li>
      <li>Mark a todo as completed</li>
      <li>Hightlight the passed todo task</li>
      <li>Next step: Analysis & Predict</li>
    </ul>
    <p>
      I need to consider the QPS.The The reasons QPS plays a big role are below:
    </p>
    <ul>
      <li>QPS decides that type web server</li>
      <li>QPS decides the relationship between web server and database</li>
    </ul>
    <p>For this practice, I assumed the QPS is under 100. A laptop will handle it all. Since I planned to deploy my project to heroku, I would use a web server. And a web server can handle 1k QPS.</p>
    <p>Since I am really not going use all 1k QPS, a SQL database would be ideal, I chose PostgreSQL.</p>
    <p>Next step: <kbd>service</kbd>. In this case, all I need is the sorted features.</p>
    <p>Now, I looked at <kbd>storage</kbd>.</p>
    <br/>
    <p>I would need to store data for todos and users. Now it looks like this:</p>
    <ul>
    <li>User Service ===> SQL</li>
    <li>Todo Service ===> SQL</li>
    </ul>

    <p>Next step: <kbd>schema</kbd>.</p>
    <span class="label label-success">User service:</span>
    <ul>
      <li>username</li>
      <li>password</li>
      <li>password_confirmation</li>
    </ul>
    <span class="label label-success">Todo service:</span>
    <ul>
      <li>title</li>
      <li>deadline</li>
      <li>completed</li>
      <li>detail</li>
      <li>overdue</li>
      <li>user_id (foreign key)</li>
    </ul>
    <p>
    I added a session service to help existing user to login.</p>

    <p>Now <kbd>user story</kbd>:</p>

    <p ALIGN=CENTER>User == 1. login/register ==> Web Server ==> 2. Get user information ==> User table</p><br>
    <p ALIGN=CENTER>User Table ==> 3 send the information back ==> Web server ==> 4. get todos ==> Todo table</p><br>
    <p ALIGN=CENTER>Todo table ==> 5. feed back todo list ==> Web Server ==> 6. Display ==> User</p><br>

    <p>Since I have the user story layout, I start to write tests to controller, model and view.</p>

    <p>Once I have my expectation setup, I can start code the real controller, model and view to pass all the tests.</p><br>

    <p>I made sure all tests passed.</p>

    <p>Last step: <kbd>deploy</kbd>.</p>
</div>

<div class="col-md-8">
    <h3>Time Management</h3>
    <hr>
    <p>Since I expect to make this project under 10 hours, I decided to time box my tasks:</p>

    <ul>
        <li>Design, set up Trello board and development environment: 1hr </li>
        <li>User login, register and logout: 2hr </li>
        <li>Display todos: 1hr </li>
        <li>View todo: 0.5hr </li>
        <li>Add todo: 1hr </li>
        <li>Delete todo: 0.5hr </li>
        <li>Mark as completed: 1hr </li>
        <li>HighLight: 1hr </li>
        <li>Styling: 1hr </li>
        <li>Edit README: 1hr</li>
    </ul>
    I used <a href="https://trello.com/b/nXlFFEu0/todo-list">Trello Board</a>  to keep my task on track.
</div>
<div class="col-md-8">
  <h3>Gems</h3>
  <hr>
  <ul>
    <li>Use postgresql as the database for Active Record</li>
    <li>Use bycrypt has_secure_password</li>
    <li>Use RSpec and Capybara to do the testing</li>
  </ul>
</div>
<div class="col-md-8">
    <h3>Installing</h3>
    <hr>
    <p>For online access to the web app, please visit https://thawing-chamber-42985.herokuapp.com/</p><br>

    <p>To run this app on your local machine, navigate to your repository folder and run the following cmd in terminal</p>

    <code>git clone https://github.com/paulliu87/todos.git</code><br><br>

    <p>Once the project is downloaded, run the cmd to access the folder</p>

    <code>cd todos</code><br><br>

    <p>Install gems</p>

    <code>bundle install</code><br><br>

    <p>Migrate the database</p>

    <code>bundle exec rake db:migrate</code><br><br>

    <p>Start the server</p>

    <code>rails server</code><br><br>

    <p>Now, you can open a chrome and enter <kbd>localhost:3000</kbd> to use the web app.</p>

    <p>To deploy this project to heroku, make sure you have a heroku account.</p>
</div>

<div class="col-md-8">
    <h3>Running the tests</h3>
    <hr>
    <p>There are over 30 RSpec tests for controller, model, and view.</p>

    <p>To run all the tests on the terminal, run the command below:</p>

    <code>bundle exec rspec spec</code><br><br>

    <p>To run the tests for specific controller or for specific unit method, follow the pattern as follow:</p>

    <code>bundle exec rspec spec/controllers/users_controller_spec.rb</code>

    <code>bundle exec rspec spec/controllers/users_controller_spec.rb:50</code>
    </p>
</div>

<div class="col-md-8">
    <h3>Deployment</h3>
    <hr>
    <a href="https://thawing-chamber-42985.herokuapp.com/">TODOs - Heroku site</a><br><br>

    <p>Run the following command in the terminal</p>

    <code>heroku create</code><br><br>

    <p>Migrate pg db</p>

    <code>heroku run rake db:migrate</code><br><br>

    <p>Open the app in the terminal</p>

    <code>heroku open</code><br>
</div>

<div class="col-md-8">
    <h3>Support Documents</h3>
    <hr>
    <ul>
        <li><a href="http://guides.rubyonrails.org/">Rails Doc.</a> - Ruby on Rails</li>
        <li><a href="https://stackoverflow.com/">Stack Overflow</a> - Very Helpful answers</li>
        <li><a href="https://relishapp.com/rspec">Relish</a> - RSpec Relish</li>
        <li><a href="https://dashboard.heroku.com/apps">Heroku</a> - Heroku deployment</li>
        <li><a href="https://trello.com/b/nXlFFEu0/todo-list">Trello</a> - Project Management Tool</li>
    </ul>
</div>
<div class="col-md-8">
    <h3>Version Control</h3>
    <hr>
    <p>
        I created a new branch everytime I was working on a new feature.
        <ul>
            <li>! [bootstrap] Add boostrap style </li>
            <li>! [changestate] changing state between login ad logout </li>
            <li>! [deploy] highlight the todo task is overdue </li>
            <li>! [homepage] create a landingpage</li>
            <li>! [master] make a readme file </li>
            <li>! [readme] highlight the todo task is overdue </li>
            <li>! [session] add session controller to pass all the tests </li>
            <li>! [todos] highlight the todo task is overdue </li>
            <li>! [user] init sessions</li>
        </ul>
    </p>
</div>
<div class="col-md-8">
    <h3>Authors</h3>
    <hr>
    Paul Liu - Initial work - <a href="https://github.com/paulliu87/todos">TODOs</a>
</div>

app/views/layouts/_calendar.html.erb
<div class="month">
  <ul>
    <li class="prev"><%= link_to "<", date: @date.prev_month %></li>
    <li class="next"><%= link_to ">", date: @date.next_month %></li>
    <li>
      <%= @date.strftime("%B") %><br>
      <span style="font-size:18px"><%= @date.strftime("%Y") %></span>
    </li>
  </ul>
</div>
<%= calendar @date do |date| %>
  <%= date.day %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="col-xs-12 navbar-inverse navbar-fixed-bottom">
  <div class="row" id="bottomNav">
    <div class="col-xs-4 text-center"><a href="#"><i class="glyphicon glyphicon-circle-arrow-left"></i><br>Link</a></div>
    <div class="col-xs-4 text-center"><a href="#"><i class="glyphicon glyphicon-circle-arrow-down"></i><br>Link</a></div>
    <div class="col-xs-4 text-center"><a href="#"><i class="glyphicon glyphicon-circle-arrow-right"></i><br>Link</a></div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<h3>Recently completed</h3>
<% if current_user %>
  <div class="recently-completed">
    <% @recent_todos.each do |todo| %>
      <div class="row">
        <a href="/users/<%= params[:user_id] %>/todos/<%= todo.id %>" data-list-id="<%= todo.id %>" class="list-group-item list-group-item-action clearfix list-group-item-success">
          <span class="glyphicon glyphicon-ok-sign"></span>
          <%= todo.title %>
          <span class="pull-right">
            <span class="glyphicon glyphicon-step-backward"></span>
          </span>
        </a>
      </div>
    <% end %>
  </div>
<% end %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todos</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" >
  </head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">TODOs</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if session[:user_id] %>
          <li>
            <a href="/users/<%= session[:user_id] %>/todos"><%= User.find(session[:user_id]).username %></a>
          </li>
          <li>
            <a href="/users/<%= session[:user_id] %>/todos/new">Add TODO</a>
          </li>
          <li>
            <%= link_to 'Log out', logout_path %>
          </li>
          <% else %>
          <li>
            <%= link_to 'Log in', login_path %>
          </li>
          <li>
            <%= link_to "Sign Up", signup_path %>
          </li>
          <% end %>
        </ul>
        <% if session[:user_id] %>
          <%= form_tag(user_todos_path(session[:user_id]), :action => "index", :method => "get", :id => "search-form", :class => "form-inline") do %>
            <div class="input-group">
              <%= text_field_tag :search, params[:search], placeholder: "Search Todos", class: "form-control" %>
              <span class="input-group-btn"><%= submit_tag "Search", :class => "btn btn-default" %></span>
            </div>
          <% end %>
        <% end %>
      </div>
    </nav>
    <div class="container">
      <div class="col-md-7 content">
        <%= yield %>
      </div>
      <div class="col col-md-4 col-md-offset-1 sidebar">
        <%= yield :sidebar %>
      </div>
      <div class="col col-md-4 col-md-offset-1 calendar">
        <%= yield :calendar %>
      </div>
      <!-- <div class='col col-xs-10 footer'>
        <%= yield :footer %>
      </div> -->
    </div>
  </body>
  <footer>
    <div id="mobile-footer">
      <div class="col-xs-12 navbar-fixed-bottom">
        <div class="row" id="bottomNav">
          <% if session[:user_id] %>
            <div class="col-xs-4 text-center"><a href="/users/<%= session[:user_id] %>/todos"><i class="glyphicon glyphicon-list"></i></a></div>
            <div class="col-xs-4 text-center"><a href="/users/<%= session[:user_id] %>"><i class="glyphicon glyphicon-user"></i></a></div>
            <div class="col-xs-4 text-center"><a href="/logout"><i class="glyphicon glyphicon-log-out"></i></a></div>
          <% else %>
            <div class="col-xs-4 text-center"><a href="/"><i class="glyphicon glyphicon-circle-arrow-left"></i></a></div>
            <div class="col-xs-4 text-center"><a href="/users/<%= session[:user_id] %>"><i class="glyphicon glyphicon-circle-arrow-down"></i></a></div>
            <div class="col-xs-4 text-center"><a href="/login"%>><i class="glyphicon glyphicon-circle-arrow-down"></i></a></div>
          <% end %>
          <!-- <div class="col-xs-4 text-center"><a href="#"><i class="glyphicon glyphicon-circle-arrow-left"></i><br>Link</a></div>
          <div class="col-xs-4 text-center"><a href="#"><i class="glyphicon glyphicon-circle-arrow-down"></i><br>Link</a></div>
          <div class="col-xs-4 text-center"><a href="#"><i class="glyphicon glyphicon-circle-arrow-right"></i><br>Link</a></div> -->
        </div>
      </div>
    </div>
  </footer>
</html>

app/views/todos/edit.html.erb
<div class="row">
    <div class="col-md-1 col-xs-2">
        <span class="text">Title:</span>
    </div>
    <div class="col-md-5 col-xs-10">
        <span class="text-muted"><%= @todo.title %></span>
    </div>
</div><br>
<div class="row">
    <div class="col-md-1 col-xs-2">
        <span class="text">Deadline:</span>
    </div>
    <div class="col-md-5 col-xs-10">
        <span class="text-muted"><%= @todo.deadline %></span>
    </div>
</div><br>
<div class="row">
    <div class="col-md-1 col-xs-2">
        <span class="text">Complete:</span>
    </div>
    <div class="col-md-5 col-xs-10">
        <span class="text-muted"><%= @todo.completed %></span>
    </div>
</div><br>
<div class="row">
    <div class="col-md-1 col-xs-2">
        <span class="text">Detail:</span>
    </div>
    <div class="col-md-5 col-xs-10">
        <span class="text-muted"><%= @todo.detail %></span>
    </div>
</div><br>
<div class="row">
    <%= link_to 'Back', { :controller => 'todos', :action => 'show', :id => @todo.id },
    { :method => :get, :class => "btn btn-default", :role => "button"} %>
</div>

app/views/todos/index.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<% end %>
<% content_for(:calendar) do %>
  <%= render :partial => "layouts/calendar" %>
<% end %>
<div class="list-group">
  <% if @todos != nil %>
    <% @todos.each do |key, value| %>
      <div class="row calendar-header">
        <div class="cal-section col-md-1 col-xs-2">
          <time class="icon" data-calendar-id="<%= key.to_s %>">
            <p><%= key.to_s[5..6] %></p>
            <div class="cal-top"></div>
            <span><%= key.to_s[8..9] %></span>
          </time>
        </div>
        <img src="/images/summer.jpg"  class="pull-right col-md-10 col-xs-9 img-reponsive img-rounded list-group-item list-group-item-action clearfix" />
      </div>
      <% value.each do |todo| %>
        <div class="row uncompleted-todos">
          <% if todo.overdue %>
            <a href="/users/<%= params[:user_id] %>/todos/<%= todo.id %>" data-list-id="<%= todo.id %>" class="pull-right col-md-10 col-xs-9 list-group-item list-group-item-action clearfix list-group-item-danger">
              <%= todo.title %>
              <span class="pull-right">
                <span class="glyphicon glyphicon-edit"></span>
                <span class="glyphicon glyphicon-trash"></span>
                <span class="glyphicon glyphicon-ok"></span>
              </span>
              <br>
              <span>
                <% if todo.detail != nil %>
                  <%= todo.detail %>
                <% end %>
                <%= todo.deadline %>
              </span>
            </a>
          <% else %>
            <a href="/users/<%= params[:user_id] %>/todos/<%= todo.id %>" data-list-id="<%= todo.id %>" class="pull-right col-md-10 col-xs-9 list-group-item list-group-item-action clearfix">
              <%= todo.title %>
              <span class="pull-right">
                <span class="glyphicon glyphicon-edit"></span>
                <span class="glyphicon glyphicon-trash"></span>
                <span class="glyphicon glyphicon-ok"></span>
              </span>
              <br>
              <% if todo.detail != nil %>
                <%= todo.detail %>
              <% end %>
              <%= todo.deadline %>
            </a>
          <% end %>
        </div>
      <% end %>
      <br>
    <% end %>
  <% end %>
</div>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= form_for :todo, url: user_todos_path do |f| %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :starts_at %><br>
        <%= f.date_select :deadline %>
    </p>

    <p>
        <%= f.label :starts_at %><br>
        <%= f.time_select :deadline, :ignore_date => true %>
    </p>

    <p>
        <%= f.label :complete %><br>
        <%= f.check_box :completed %>
    </p>

    <p>
        <%= f.label :detail %><br>
        <%= f.text_area :detail %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/todos/show.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-1">
          <span class="text">Title:</span>
      </div>
      <div class="col-md-5">
          <span class="text-muted"><%= @todo.title %></span>
      </div>
  </div><br>
  <div class="row">
      <div class="col-md-1">
          <span class="text">Deadline:</span>
      </div>
      <div class="col-md-5">
          <span class="text-muted"><%= @todo.deadline %></span>
      </div>
  </div><br>
  <div class="row">
      <div class="col-md-1">
          <span class="text">Complete:</span>
      </div>
      <div class="col-md-5">
          <span class="text-muted"><%= @todo.completed %></span>
      </div>
  </div><br>
  <div class="row">
      <div class="col-md-1">
          <span class="text">Detail:</span>
      </div>
      <div class="col-md-5">
          <span class="text-muted"><%= @todo.detail %></span>
      </div>
  </div><br>
  <div class="row">
      <%= link_to 'Back', { :controller => 'todos', :action => 'index', :id => @todo.id },
      { :method => :get, :class => "btn btn-default", :role => "button"} %>
      <%= link_to 'Delete', { :controller => 'todos', :action => 'destroy', :id => @todo.id },
      { :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-default", :role => "button"} %>
      <%= link_to 'Mark as Completed', { :controller => 'todos', :action => 'completed', :id => @todo.id },
      { :method => :put, :class => "btn btn-default", :role => "button"} %>
  </div>
</div>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<%= form_for @user do |f| %>
    <!-- error message display -->
    <% if @user.errors.any? %>
        <div class="error_messsages" >
            <h2>Form is invalid</h2>
            <ul>
                <% @user.errors.full_messages.each do |message| %>
                    <li>
                        <%= message %>
                    </li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <!-- Actual form -->
    <div>
        <%= f.label :username %><br />
        <%= f.text_field :username %>
    </div>

    <div>
        <%= f.label :password %><br />
        <%= f.password_field :password %>
    </div>
    <div>
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation %>
    </div>
    <div>
        <%= f.submit %>
    </div>
<% end %>